const state={csrf:'',admin:null,participants:[],prizes:[],results:[],csvRows:[]};const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function fmt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Recife',dateStyle:'short',timeStyle:'short'}).format(d)}
function toast(m,t='success'){const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;$('toasts').appendChild(e);setTimeout(()=>e.remove(),3500)}
async function api(url,opt={}){const c={method:opt.method||'GET',headers:{},credentials:'same-origin'};if(opt.body!==undefined){c.headers['Content-Type']='application/json';c.body=JSON.stringify(opt.body)}if(state.csrf&&c.method!=='GET')c.headers['X-CSRF-Token']=state.csrf;const r=await fetch(url,c);let d={};try{d=await r.json()}catch{}if(r.status===401&&!url.includes('/login')){showLogin();throw new Error('Sua sessão expirou. Entre novamente.')}if(!r.ok||d.ok===false)throw new Error(d.error||d.erro||'Não foi possível concluir a operação.');return d}
function showLogin(){$('appShell').classList.add('hidden');$('loginPage').classList.remove('hidden');state.csrf=''}function showApp(){$('loginPage').classList.add('hidden');$('appShell').classList.remove('hidden');$('adminEmail').textContent=state.admin?.email||'Administrador'}
function debounce(fn,ms=300){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function view(name){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('active',e.id===`view-${name}`));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.view===name));const titles={dashboard:['PAINEL','Visão geral'],participants:['GESTÃO','Participantes'],prizes:['GESTÃO','Prêmios'],results:['HISTÓRICO','Resultados'],payments:['FINANCEIRO','Dados bancários'],settings:['CAMPANHA','Configurações']};$('pageEye').textContent=titles[name][0];$('pageTitle').textContent=titles[name][1];$('sidebar').classList.remove('open');if(name==='dashboard')loadDashboard();if(name==='participants')loadParticipants();if(name==='prizes')loadPrizes();if(name==='results')loadResults();if(name==='payments')loadPayments();if(name==='settings')loadSettings()}
async function loadDashboard(){try{const{dashboard:d,system:s}=await api('/api/admin/dashboard');const ms=[['Participantes',d.totalParticipants],['Ativos',d.activeParticipants],['Entraram',d.enteredParticipants],['Concluíram',d.completedParticipants],['Cartas ativas',d.totalPrizeCards]];$('metrics').innerHTML=ms.map(x=>`<article class="metric"><span>${x[0]}</span><strong>${Number(x[1]||0)}</strong></article>`).join('');$('recentBody').innerHTML=d.recentResults.length?d.recentResults.map(x=>`<tr><td class="person"><strong>${esc(x.participant?.name)}</strong><span>${esc(x.participant?.code)}</span></td><td><strong>${esc(x.prize)}</strong></td><td>${esc(fmt(x.drawnAt))}</td></tr>`).join(''):'<tr><td colspan="3">Nenhum sorteio concluído.</td></tr>';const h=[[s.databaseConfigured,'Banco persistente',s.databaseConfigured?'Postgres conectado.':'Modo local. Configure DATABASE_URL antes de publicar.'],[s.adminCredentialsConfigured,'Acesso administrativo',s.adminCredentialsConfigured?'Credenciais protegidas..':'Credenciais locais de demonstração em uso.'],[s.whatsappTokenConfigured,'Integração WhatsApp',s.whatsappTokenConfigured?(s.whatsappEnabled?'Token configurado e notificações ativadas.':'Token configurado; notificações desativadas.'):'Token não configurado; o restante funciona normalmente.']];$('health').innerHTML=h.map(x=>`<div class="health-item"><div class="health-icon ${x[0]?'':'warn'}">${x[0]?'✓':'!'}</div><div><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join('');const w=[];if(!s.databaseConfigured)w.push('Conecte um Postgres e configure DATABASE_URL antes de publicar.');if(!s.adminCredentialsConfigured)w.push('Defina ADMIN_EMAIL, ADMIN_PASSWORD e SESSION_SECRET.');$('systemAlert').textContent=w.join(' ');$('systemAlert').classList.toggle('hidden',!w.length)}catch(e){toast(e.message,'error')}}
function status(x){if(!x.active)return'<span class="badge inactive">Inativo</span>';if(x.participation?.finalized)return'<span class="badge done">Concluído</span>';if(x.participation)return'<span class="badge entered">Entrou</span>';return'<span class="badge active">Disponível</span>'}
async function loadParticipants(){try{const q=encodeURIComponent($('participantSearch').value.trim()),st=encodeURIComponent($('participantStatus').value),{participants:p}=await api(`/api/admin/participants?search=${q}&status=${st}`);state.participants=p;$('participantCount').textContent=p.length;$('participantsEmpty').classList.toggle('hidden',p.length>0);$('participantsBody').innerHTML=p.map(x=>`<tr><td class="person"><strong>${esc(x.name)}</strong><span>${x.fixedPrize?'Fixo: '+esc(x.fixedPrize):'Sorteio normal'}</span></td><td><strong>${esc(x.code)}</strong></td><td>${esc(x.contact||'—')}</td><td>${status(x)}</td><td>${x.participation?.finalized?`<strong>${esc(x.participation.prize)}</strong><br><small>Carta ${x.participation.selectedCard}</small>`:'—'}</td><td><div class="row-actions">${x.participation?`<button class="icon" data-action="resetP" data-id="${x.id}" title="Liberar">↻</button>`:''}<button class="icon" data-action="editP" data-id="${x.id}">✎</button><button class="icon danger" data-action="deleteP" data-id="${x.id}">×</button></div></td></tr>`).join('')}catch(e){toast(e.message,'error')}}
async function loadPrizes(){try{const{prizes:p}=await api('/api/admin/prizes');state.prizes=p;$('prizeCount').textContent=p.length;$('cardsSummary').textContent=`${p.filter(x=>x.active).reduce((s,x)=>s+Number(x.quantity||0),0)} cartas ativas`;$('prizesBody').innerHTML=p.length?p.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${x.quantity}</td><td><span class="badge ${x.active?'active':'inactive'}">${x.active?'Ativo':'Inativo'}</span></td><td><div class="row-actions"><button class="icon" data-action="editPrize" data-id="${x.id}">✎</button><button class="icon danger" data-action="deletePrize" data-id="${x.id}">×</button></div></td></tr>`).join(''):'<tr><td colspan="4">Nenhum prêmio cadastrado.</td></tr>';fillFixed()}catch(e){toast(e.message,'error')}}
async function loadResults(){try{const q=encodeURIComponent($('resultSearch').value.trim()),p=encodeURIComponent($('resultPrize').value.trim()),{results:r}=await api(`/api/admin/results?search=${q}&prize=${p}&limit=1000`);state.results=r;$('resultCount').textContent=r.length;$('resultsEmpty').classList.toggle('hidden',r.length>0);$('resultsBody').innerHTML=r.map(x=>`<tr><td class="person"><strong>${esc(x.participant?.name)}</strong><span>${esc(x.participant?.contact||'')}</span></td><td>${esc(x.participant?.code)}</td><td>${x.selectedCard||'—'}</td><td><strong>${esc(x.prize)}</strong></td><td>${esc(fmt(x.enteredAt))}</td><td>${esc(fmt(x.drawnAt))}</td><td>${x.paymentAt?`<strong>✅ Recebidos</strong><br><small>${esc(fmt(x.paymentAt))} • WhatsApp: ${esc(x.paymentNotificationStatus||'pending')}</small><br><button class=\"icon\" data-action=\"viewPayment\" data-id=\"${esc(x.id)}\">Ver dados</button>`:'<span class=\"badge inactive\">Pendente</span>'}</td></tr>`).join('')}catch(e){toast(e.message,'error')}}
async function loadSettings(){try{const{settings:s}=await api('/api/admin/settings');$('setName').value=s.campaignName||'';$('setTag').value=s.campaignTag||'';$('setLogo').value=s.logoUrl||'';$('setInstruction').value=s.instruction||'';$('setPrimary').value=s.primaryColor||'#255a9c';$('setSecondary').value=s.secondaryColor||'#226f2b';$('setWhatsapp').checked=Boolean(s.whatsappEnabled);$('setNumber').value=s.adminWhatsapp||''}catch(e){toast(e.message,'error')}}
function fillFixed(sel=''){const o=['<option value="">Sorteio normal</option>',...state.prizes.filter(x=>x.active).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`)];if(sel&&!state.prizes.some(x=>x.name===sel))o.push(`<option value="${esc(sel)}">${esc(sel)} (personalizado)</option>`);$('participantFixed').innerHTML=o.join('');$('participantFixed').value=sel}
async function openParticipant(x=null){if(!state.prizes.length)await loadPrizes();$('participantId').value=x?.id||'';$('participantName').value=x?.name||'';$('participantCode').value=x?.code||'';$('participantContact').value=x?.contact||'';$('participantActive').checked=x?x.active:true;fillFixed(x?.fixedPrize||'');$('participantTitle').textContent=x?'Editar participante':'Novo participante';$('participantError').textContent='';$('participantDialog').showModal()}
function openPrize(x=null){$('prizeId').value=x?.id||'';$('prizeName').value=x?.name||'';$('prizeQuantity').value=x?.quantity||1;$('prizeActive').checked=x?x.active:true;$('prizeTitle').textContent=x?'Editar prêmio':'Novo prêmio';$('prizeError').textContent='';$('prizeDialog').showModal()}
function csvLine(line,d){const a=[];let v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===d&&!q){a.push(v.trim());v=''}else v+=c}a.push(v.trim());return a}function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('O CSV precisa ter cabeçalho e dados.');const d=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',',h=csvLine(lines[0],d).map(norm),find=a=>h.findIndex(x=>a.includes(x)),idx={code:find(['codigo','code','cod']),name:find(['nome','name','participante']),contact:find(['contato','contact','whatsapp','telefone']),active:find(['ativo','active','status']),fixed:find(['premiofixo','fixedprize','premio'])};if(idx.code<0||idx.name<0)throw new Error('O CSV precisa das colunas codigo e nome.');return lines.slice(1).map(l=>{const v=csvLine(l,d),ar=idx.active>=0?String(v[idx.active]||'').toLowerCase():'true';return{code:v[idx.code],name:v[idx.name],contact:idx.contact>=0?v[idx.contact]:'',active:!['false','0','nao','não','inativo'].includes(ar),fixedPrize:idx.fixed>=0?v[idx.fixed]:''}}).filter(x=>x.code||x.name)}
function csvEsc(v){const t=String(v??'');return/[;"\n]/.test(t)?`"${t.replaceAll('"','""')}"`:t}function exportCsv(){if(!state.results.length)return toast('Não há resultados para exportar.','error');const rows=[['codigo','nome','contato','carta','premio','entrou_em','sorteado_em','status_pagamento','favorecido','cpf_cnpj','banco','agencia','conta','operacao','chave_pix','recebido_em','status_whatsapp'],...state.results.map(x=>[x.participant?.code,x.participant?.name,x.participant?.contact,x.selectedCard,x.prize,fmt(x.enteredAt),fmt(x.drawnAt),x.paymentAt?'Recebido':'Pendente',x.paymentData?.favorecido,x.paymentData?.documento,x.paymentData?.banco,x.paymentData?.agencia,x.paymentData?.conta,x.paymentData?.operacao,x.paymentData?.chavePix,fmt(x.paymentAt),x.paymentNotificationStatus])],blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvEsc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`resultados-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}

let paymentRows=[],paymentToCopy='';
async function loadPayments(){
  try{
    const q=encodeURIComponent($('paymentSearch').value.trim());
    const {results:r}=await api(`/api/admin/results?search=${q}&limit=2000`);
    paymentRows=r;
    const received=r.filter(x=>Boolean(x.paymentAt&&x.paymentData)).length;
    $('paymentSummary').textContent=`${received} recebido(s) • ${r.length-received} pendente(s)`;
    const filter=$('paymentFilter').value;
    const rows=r.filter(x=>filter==='all'||(filter==='received'?Boolean(x.paymentAt&&x.paymentData):!x.paymentAt));
    $('paymentsEmpty').classList.toggle('hidden',rows.length>0);
    $('paymentsBody').innerHTML=rows.map(x=>{
      const received=Boolean(x.paymentAt&&x.paymentData);
      const wa=x.paymentNotificationStatus==='sent'?'Enviado':x.paymentNotificationStatus==='failed'?'Falhou':x.paymentNotificationStatus==='disabled'?'Desativado':x.paymentNotificationStatus||'Pendente';
      return `<tr><td class="person"><strong>${esc(x.participant?.name||'—')}</strong><span>${esc(x.participant?.contact||'')}</span></td><td>${esc(x.participant?.code||'—')}</td><td>${esc(x.prize||'—')}</td><td>${received?'<span class="payment-ok">✓ Recebido</span>':'<span class="badge inactive">Aguardando preenchimento</span>'}</td><td>${esc(fmt(x.paymentAt))}</td><td>${received?esc(wa):'—'}</td><td>${received?`<button class="btn secondary" data-action="viewPayment" data-id="${esc(x.id)}">Ver dados</button>`:'—'}</td></tr>`;
    }).join('');
  }catch(e){toast(e.message,'error');$('paymentsBody').innerHTML='<tr><td colspan="7">Não foi possível carregar os dados. Tente atualizar.</td></tr>'}
}
function showPayment(x){
  if(!x?.paymentData)return toast('Dados ainda não recebidos.','error');
  const d=x.paymentData;
  const entries=[['Favorecido',d.favorecido],['CPF/CNPJ',d.documento],['Banco',d.banco],['Agência',d.agencia],['Conta',d.conta],['Operação',d.operacao],['Chave Pix',d.chavePix]];
  $('paymentDialogTitle').textContent=x.participant?.name||'Parceiro';
  $('paymentDialogMeta').textContent=`Código: ${x.participant?.code||'—'} • Prêmio: ${x.prize||'—'} • Enviado em: ${fmt(x.paymentAt)}`;
  $('paymentDialogFields').innerHTML=entries.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v||'—')}</strong></div>`).join('');
  paymentToCopy=`Parceiro: ${x.participant?.name||''}\nCódigo: ${x.participant?.code||''}\nPrêmio: ${x.prize||''}\n`+entries.map(([k,v])=>`${k}: ${v||'—'}`).join('\n');
  $('paymentDialog').showModal();
}
function exportPayments(){
  const rows=[['codigo','parceiro','contato','premio','status','favorecido','cpf_cnpj','banco','agencia','conta','operacao','chave_pix','recebido_em','status_whatsapp'],...paymentRows.map(x=>[x.participant?.code,x.participant?.name,x.participant?.contact,x.prize,x.paymentAt?'Recebido':'Pendente',x.paymentData?.favorecido,x.paymentData?.documento,x.paymentData?.banco,x.paymentData?.agencia,x.paymentData?.conta,x.paymentData?.operacao,x.paymentData?.chavePix,fmt(x.paymentAt),x.paymentNotificationStatus])];
  const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvEsc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});
  const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='dados-bancarios-totalcash.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);
}

document.addEventListener('click',async e=>{const v=e.target.closest('[data-view]');if(v)return view(v.dataset.view);const c=e.target.closest('[data-close]');if(c)return $(c.dataset.close).close();const a=e.target.closest('[data-action]');if(!a)return;const id=a.dataset.id;try{if(a.dataset.action==='viewPayment'){const x=[...paymentRows,...state.results].find(x=>String(x.id)===String(id));return showPayment(x);}if(a.dataset.action==='editP')return openParticipant(state.participants.find(x=>x.id===id));if(a.dataset.action==='deleteP'){if(!confirm('Excluir este participante e o histórico dele?'))return;await api('/api/admin/participants',{method:'POST',body:{action:'delete',id}});toast('Participante excluído.');return Promise.all([loadParticipants(),loadDashboard()])}if(a.dataset.action==='resetP'){if(!confirm('Liberar este participante para jogar novamente? O resultado anterior será removido.'))return;await api('/api/admin/participants',{method:'POST',body:{action:'reset',id}});toast('Participante liberado.');return Promise.all([loadParticipants(),loadDashboard()])}if(a.dataset.action==='editPrize')return openPrize(state.prizes.find(x=>x.id===id));if(a.dataset.action==='deletePrize'){if(!confirm('Excluir este prêmio?'))return;await api('/api/admin/prizes',{method:'POST',body:{action:'delete',id}});toast('Prêmio excluído.');return Promise.all([loadPrizes(),loadDashboard()])}}catch(err){toast(err.message,'error')}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const d=await api('/api/admin/login',{method:'POST',body:{email:$('loginEmail').value,password:$('loginPassword').value}});state.csrf=d.csrf;state.admin=d.admin;showApp();view('dashboard');if(d.warning)toast(d.warning,'error')}catch(err){$('loginError').textContent=err.message}});$('logoutBtn').onclick=async()=>{try{await api('/api/admin/logout',{method:'POST',body:{}})}catch{}showLogin()};$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('newParticipantBtn').onclick=()=>openParticipant();$('newPrizeBtn').onclick=()=>openPrize();$('generateCode').onclick=()=>{$('participantCode').value=String(Math.floor(100000+Math.random()*900000))};$('participantSearch').addEventListener('input',debounce(loadParticipants));$('participantStatus').onchange=loadParticipants;$('resultSearch').addEventListener('input',debounce(loadResults));$('resultPrize').addEventListener('input',debounce(loadResults));$('exportBtn').onclick=exportCsv;$('paymentSearch').addEventListener('input',debounce(loadPayments));$('paymentFilter').onchange=loadPayments;$('paymentRefresh').onclick=loadPayments;$('paymentExport').onclick=exportPayments;$('paymentCopy').onclick=async()=>{try{await navigator.clipboard.writeText(paymentToCopy);toast('Dados copiados.')}catch{toast('Não foi possível copiar.','error')}};
$('participantForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('participantId').value,p={name:$('participantName').value,code:$('participantCode').value,contact:$('participantContact').value,fixedPrize:$('participantFixed').value,active:$('participantActive').checked};try{await api('/api/admin/participants',{method:'POST',body:{action:id?'update':'create',id,participant:p}});$('participantDialog').close();toast(id?'Participante atualizado.':'Participante criado.');await Promise.all([loadParticipants(),loadDashboard()])}catch(err){$('participantError').textContent=err.message}});$('prizeForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('prizeId').value,p={name:$('prizeName').value,quantity:Number($('prizeQuantity').value),active:$('prizeActive').checked};try{await api('/api/admin/prizes',{method:'POST',body:{action:id?'update':'create',id,prize:p}});$('prizeDialog').close();toast(id?'Prêmio atualizado.':'Prêmio criado.');await Promise.all([loadPrizes(),loadDashboard()])}catch(err){$('prizeError').textContent=err.message}});$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();$('settingsStatus').textContent='Salvando...';try{await api('/api/admin/settings',{method:'POST',body:{settings:{campaignName:$('setName').value,campaignTag:$('setTag').value,logoUrl:$('setLogo').value,instruction:$('setInstruction').value,primaryColor:$('setPrimary').value,secondaryColor:$('setSecondary').value,whatsappEnabled:$('setWhatsapp').checked,adminWhatsapp:$('setNumber').value}}});$('settingsStatus').textContent='Alterações salvas.';toast('Configurações atualizadas.')}catch(err){$('settingsStatus').textContent=err.message;toast(err.message,'error')}});
$('importBtn').onclick=()=>{state.csvRows=[];$('csvFile').value='';$('importPreview').classList.add('hidden');$('importError').textContent='';$('importSubmit').disabled=true;$('importDialog').showModal()};$('csvFile').onchange=async()=>{try{const f=$('csvFile').files[0];if(!f)return;state.csvRows=parseCsv(await f.text());$('importPreview').textContent=`${state.csvRows.length} participantes prontos para importar.`;$('importPreview').classList.remove('hidden');$('importSubmit').disabled=!state.csvRows.length}catch(err){state.csvRows=[];$('importSubmit').disabled=true;$('importError').textContent=err.message}};$('importForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.csvRows.length)return;$('importSubmit').disabled=true;try{const{summary:s}=await api('/api/admin/participants',{method:'POST',body:{action:'import',mode:$('importMode').value,rows:state.csvRows}});$('importDialog').close();toast(`${s.created} criados, ${s.updated} atualizados e ${s.skipped} ignorados.${s.errors.length?' '+s.errors.length+' erros.':''}`);await Promise.all([loadParticipants(),loadDashboard()])}catch(err){$('importError').textContent=err.message}finally{$('importSubmit').disabled=false}});
(async()=>{try{const d=await api('/api/admin/session');state.csrf=d.csrf;state.admin=d.admin;showApp();view('dashboard')}catch{showLogin()}})();
