const fs=require('fs'),path=require('path');const{temBanco,query,ensureSchema}=require('./_db');const{gerarId,normalizarCodigo,normalizarTexto}=require('./_config');const{DEFAULT_SETTINGS,DEFAULT_PARTICIPANTS,DEFAULT_PRIZES}=require('./_seed');
const dir=path.join(process.cwd(),'dados'),file=path.join(dir,'sistema.json');let cache=null,initPromise=null;const now=()=>new Date().toISOString();
const pubP=x=>x?{id:x.id,code:x.code,name:x.name,contact:x.contact||'',active:x.active!==false,fixedPrize:x.fixedPrize||'',createdAt:x.createdAt,updatedAt:x.updatedAt}:null;
const pubPrize=x=>x?{id:x.id,name:x.name,quantity:Number(x.quantity)||1,active:x.active!==false,createdAt:x.createdAt,updatedAt:x.updatedAt}:null;
const pubPart=x=>x?{id:x.id,participantId:x.participantId,roundId:x.roundId,prizeSnapshot:Array.isArray(x.prizeSnapshot)?x.prizeSnapshot:[],enteredAt:x.enteredAt,selectedCard:x.selectedCard||null,prize:x.prize||null,prizeId:x.prizeId||null,prizeMap:Array.isArray(x.prizeMap)?x.prizeMap:[],drawnAt:x.drawnAt||null,finalized:Boolean(x.finalized),paymentData:x.paymentData||null,paymentAt:x.paymentAt||null,paymentNotificationStatus:x.paymentNotificationStatus||'pending'}:null;
function base(){const t=now();return{version:5,settings:{...DEFAULT_SETTINGS,createdAt:t,updatedAt:t},participants:DEFAULT_PARTICIPANTS.map(x=>({id:gerarId(),code:normalizarCodigo(x.code),name:x.name,contact:x.contact||'',active:x.active!==false,fixedPrize:x.fixedPrize||'',createdAt:t,updatedAt:t})),prizes:DEFAULT_PRIZES.map(x=>({id:gerarId(),name:x.name,quantity:x.quantity,active:x.active!==false,createdAt:t,updatedAt:t})),participations:[],audit:[]}}
function load(){if(cache)return cache;fs.mkdirSync(dir,{recursive:true});if(fs.existsSync(file)){try{cache=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}}if(!cache){cache=base();save()}return cache}
function save(){if(!cache)return;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,JSON.stringify(cache,null,2),'utf8')}
async function seedDb(){await ensureSchema();const s=DEFAULT_SETTINGS;await query(`INSERT INTO campaign_settings(id,campaign_name,campaign_tag,instruction,logo_url,primary_color,secondary_color,whatsapp_enabled,admin_whatsapp)VALUES(1,$1,$2,$3,$4,$5,$6,$7,$8)ON CONFLICT(id)DO NOTHING`,[s.campaignName,s.campaignTag,s.instruction,s.logoUrl,s.primaryColor,s.secondaryColor,s.whatsappEnabled,s.adminWhatsapp]);for(const x of DEFAULT_PARTICIPANTS)await query(`INSERT INTO participants(id,code,name,contact,active,fixed_prize)VALUES($1,$2,$3,$4,$5,$6)ON CONFLICT(code)DO NOTHING`,[gerarId(),normalizarCodigo(x.code),x.name,x.contact||'',x.active!==false,x.fixedPrize||'']);for(const x of DEFAULT_PRIZES)await query(`INSERT INTO prizes(id,name,quantity,active)VALUES($1,$2,$3,$4)ON CONFLICT(name)DO NOTHING`,[gerarId(),x.name,x.quantity,x.active!==false])}
async function initialize(){if(initPromise)return initPromise;if(process.env.VERCEL&&!temBanco())throw new Error('Banco de dados não configurado. Conecte um Postgres e defina DATABASE_URL.');initPromise=temBanco()?seedDb():Promise.resolve(load());return initPromise.catch(e=>{initPromise=null;throw e})}
const mapP=r=>pubP({id:r.id,code:r.code,name:r.name,contact:r.contact,active:r.active,fixedPrize:r.fixed_prize,createdAt:r.created_at,updatedAt:r.updated_at});
const mapPrize=r=>pubPrize({id:r.id,name:r.name,quantity:r.quantity,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at});
const mapPart=r=>pubPart({id:r.id,participantId:r.participant_id,roundId:r.round_id,prizeSnapshot:r.prize_snapshot,enteredAt:r.entered_at,selectedCard:r.selected_card,prize:r.prize,prizeId:r.prize_id,prizeMap:r.prize_map,drawnAt:r.drawn_at,finalized:r.finalized,paymentData:r.payment_data,paymentAt:r.payment_at,paymentNotificationStatus:r.payment_notification_status});
async function audit(action,entity,entityId,details={}){await initialize();if(!temBanco()){const b=load();b.audit.unshift({id:gerarId(),action,entity,entityId,details,createdAt:now()});b.audit=b.audit.slice(0,1000);save();return}await query('INSERT INTO audit_logs(action,entity,entity_id,details)VALUES($1,$2,$3,$4::jsonb)',[action,entity,entityId||null,JSON.stringify(details)])}
async function getSettings(){await initialize();if(!temBanco())return{...load().settings};const r=(await query('SELECT * FROM campaign_settings WHERE id=1')).rows[0];return{campaignName:r.campaign_name,campaignTag:r.campaign_tag,instruction:r.instruction,logoUrl:r.logo_url,primaryColor:r.primary_color,secondaryColor:r.secondary_color,whatsappEnabled:r.whatsapp_enabled,adminWhatsapp:r.admin_whatsapp,createdAt:r.created_at,updatedAt:r.updated_at}}
async function updateSettings(input){const a=await getSettings(),d={campaignName:normalizarTexto(input.campaignName??a.campaignName,120)||a.campaignName,campaignTag:normalizarTexto(input.campaignTag??a.campaignTag,80),instruction:normalizarTexto(input.instruction??a.instruction,240),logoUrl:normalizarTexto(input.logoUrl??a.logoUrl,500)||'/totalcash.png',primaryColor:/^#[0-9a-f]{6}$/i.test(input.primaryColor||'')?input.primaryColor:a.primaryColor,secondaryColor:/^#[0-9a-f]{6}$/i.test(input.secondaryColor||'')?input.secondaryColor:a.secondaryColor,whatsappEnabled:Boolean(input.whatsappEnabled),adminWhatsapp:normalizarTexto(input.adminWhatsapp??a.adminWhatsapp,30).replace(/\D/g,'')};if(!temBanco()){const b=load();b.settings={...b.settings,...d,updatedAt:now()};save();await audit('update','settings','1',d);return{...b.settings}}const r=(await query(`UPDATE campaign_settings SET campaign_name=$1,campaign_tag=$2,instruction=$3,logo_url=$4,primary_color=$5,secondary_color=$6,whatsapp_enabled=$7,admin_whatsapp=$8,updated_at=NOW()WHERE id=1 RETURNING *`,[d.campaignName,d.campaignTag,d.instruction,d.logoUrl,d.primaryColor,d.secondaryColor,d.whatsappEnabled,d.adminWhatsapp])).rows[0];await audit('update','settings','1',d);return{...d,createdAt:r.created_at,updatedAt:r.updated_at}}
async function listParticipants({search='',status='all'}={}){await initialize();const t=normalizarTexto(search,100).toLowerCase();if(!temBanco()){const b=load();return b.participants.filter(x=>!t||[x.code,x.name,x.contact].some(v=>String(v||'').toLowerCase().includes(t))).filter(x=>status==='all'||(status==='active'?x.active:!x.active)).map(x=>({...pubP(x),participation:pubPart(b.participations.find(p=>p.participantId===x.id))})).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}const ps=[],f=[];if(t){ps.push(`%${t}%`);f.push(`(LOWER(p.code)LIKE $${ps.length} OR LOWER(p.name)LIKE $${ps.length} OR LOWER(p.contact)LIKE $${ps.length})`)}if(['active','inactive'].includes(status)){ps.push(status==='active');f.push(`p.active=$${ps.length}`)}const rows=(await query(`SELECT p.*,pa.id participation_id,pa.round_id,pa.prize_snapshot,pa.entered_at,pa.selected_card,pa.prize,pa.prize_id,pa.prize_map,pa.drawn_at,pa.finalized,pa.payment_data,pa.payment_at,pa.payment_notification_status FROM participants p LEFT JOIN participations pa ON pa.participant_id=p.id ${f.length?'WHERE '+f.join(' AND '):''} ORDER BY p.created_at DESC`,ps)).rows;return rows.map(r=>({...mapP(r),participation:r.participation_id?mapPart({id:r.participation_id,participant_id:r.id,round_id:r.round_id,prize_snapshot:r.prize_snapshot,entered_at:r.entered_at,selected_card:r.selected_card,prize:r.prize,prize_id:r.prize_id,prize_map:r.prize_map,drawn_at:r.drawn_at,finalized:r.finalized,payment_data:r.payment_data,payment_at:r.payment_at,payment_notification_status:r.payment_notification_status}):null}))}
async function findParticipantByCode(code){await initialize();const c=normalizarCodigo(code);if(!temBanco())return pubP(load().participants.find(x=>x.code===c));const r=(await query('SELECT * FROM participants WHERE code=$1 LIMIT 1',[c])).rows[0];return r?mapP(r):null}
async function getParticipantById(id){await initialize();if(!temBanco())return pubP(load().participants.find(x=>x.id===id));const r=(await query('SELECT * FROM participants WHERE id=$1 LIMIT 1',[id])).rows[0];return r?mapP(r):null}
function validP(i){const code=normalizarCodigo(i.code),name=normalizarTexto(i.name,160);if(!code)throw new Error('Informe o código do participante.');if(!name)throw new Error('Informe o nome do participante.');return{code,name,contact:normalizarTexto(i.contact,160),active:i.active!==false,fixedPrize:normalizarTexto(i.fixedPrize,200)}}
async function createParticipant(i){await initialize();const d=validP(i),id=gerarId();if(!temBanco()){const b=load();if(b.participants.some(x=>x.code===d.code))throw new Error('Já existe um participante com esse código.');const x={id,...d,createdAt:now(),updatedAt:now()};b.participants.push(x);save();await audit('create','participant',id,{code:d.code,name:d.name});return pubP(x)}try{const r=(await query('INSERT INTO participants(id,code,name,contact,active,fixed_prize)VALUES($1,$2,$3,$4,$5,$6)RETURNING *',[id,d.code,d.name,d.contact,d.active,d.fixedPrize])).rows[0];await audit('create','participant',id,d);return mapP(r)}catch(e){if(e.code==='23505')throw new Error('Já existe um participante com esse código.');throw e}}
async function updateParticipant(id,i){const a=await getParticipantById(id);if(!a)throw new Error('Participante não encontrado.');const d=validP({...a,...i});if(!temBanco()){const b=load();if(b.participants.some(x=>x.id!==id&&x.code===d.code))throw new Error('Já existe um participante com esse código.');const k=b.participants.findIndex(x=>x.id===id);b.participants[k]={...b.participants[k],...d,updatedAt:now()};save();await audit('update','participant',id,d);return pubP(b.participants[k])}try{const r=(await query('UPDATE participants SET code=$1,name=$2,contact=$3,active=$4,fixed_prize=$5,updated_at=NOW()WHERE id=$6 RETURNING *',[d.code,d.name,d.contact,d.active,d.fixedPrize,id])).rows[0];await audit('update','participant',id,d);return mapP(r)}catch(e){if(e.code==='23505')throw new Error('Já existe um participante com esse código.');throw e}}
async function deleteParticipant(id){await initialize();if(!temBanco()){const b=load(),n=b.participants.length;b.participants=b.participants.filter(x=>x.id!==id);b.participations=b.participations.filter(x=>x.participantId!==id);save();if(n!==b.participants.length)await audit('delete','participant',id,{});return n!==b.participants.length}const r=await query('DELETE FROM participants WHERE id=$1',[id]);if(r.rowCount)await audit('delete','participant',id,{});return Boolean(r.rowCount)}
async function resetParticipation(id){await initialize();if(!temBanco()){const b=load(),n=b.participations.length;b.participations=b.participations.filter(x=>x.participantId!==id);save();if(n!==b.participations.length)await audit('reset','participation',id,{});return n!==b.participations.length}const r=await query('DELETE FROM participations WHERE participant_id=$1',[id]);if(r.rowCount)await audit('reset','participation',id,{});return Boolean(r.rowCount)}
async function listPrizes({activeOnly=false}={}){await initialize();if(!temBanco())return load().prizes.filter(x=>!activeOnly||x.active).map(pubPrize).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));return(await query(`SELECT * FROM prizes ${activeOnly?'WHERE active=TRUE':''} ORDER BY name`)).rows.map(mapPrize)}
function validPrize(i){const name=normalizarTexto(i.name,200),quantity=Math.max(1,Math.min(500,Number(i.quantity)||1));if(!name)throw new Error('Informe o nome do prêmio.');return{name,quantity,active:i.active!==false}}
async function createPrize(i){await initialize();const d=validPrize(i),id=gerarId();if(!temBanco()){const b=load();if(b.prizes.some(x=>x.name.toLowerCase()===d.name.toLowerCase()))throw new Error('Já existe um prêmio com esse nome.');const x={id,...d,createdAt:now(),updatedAt:now()};b.prizes.push(x);save();await audit('create','prize',id,d);return pubPrize(x)}try{const r=(await query('INSERT INTO prizes(id,name,quantity,active)VALUES($1,$2,$3,$4)RETURNING *',[id,d.name,d.quantity,d.active])).rows[0];await audit('create','prize',id,d);return mapPrize(r)}catch(e){if(e.code==='23505')throw new Error('Já existe um prêmio com esse nome.');throw e}}
async function updatePrize(id,i){const a=(await listPrizes()).find(x=>x.id===id);if(!a)throw new Error('Prêmio não encontrado.');const d=validPrize({...a,...i});if(!temBanco()){const b=load(),k=b.prizes.findIndex(x=>x.id===id);b.prizes[k]={...b.prizes[k],...d,updatedAt:now()};save();await audit('update','prize',id,d);return pubPrize(b.prizes[k])}try{const r=(await query('UPDATE prizes SET name=$1,quantity=$2,active=$3,updated_at=NOW()WHERE id=$4 RETURNING *',[d.name,d.quantity,d.active,id])).rows[0];await audit('update','prize',id,d);return mapPrize(r)}catch(e){if(e.code==='23505')throw new Error('Já existe um prêmio com esse nome.');throw e}}
async function deletePrize(id){await initialize();if(!temBanco()){const b=load(),n=b.prizes.length;b.prizes=b.prizes.filter(x=>x.id!==id);save();if(n!==b.prizes.length)await audit('delete','prize',id,{});return n!==b.prizes.length}const r=await query('DELETE FROM prizes WHERE id=$1',[id]);if(r.rowCount)await audit('delete','prize',id,{});return Boolean(r.rowCount)}
async function getParticipationByParticipantId(id){await initialize();if(!temBanco())return pubPart(load().participations.find(x=>x.participantId===id));const r=(await query('SELECT * FROM participations WHERE participant_id=$1 LIMIT 1',[id])).rows[0];return r?mapPart(r):null}
async function registerEntry(p,snapshot){const old=await getParticipationByParticipantId(p.id);if(old)return{participation:old,createdNow:false};const x={id:gerarId(),participantId:p.id,roundId:gerarId('rodada-'),prizeSnapshot:snapshot,enteredAt:now(),selectedCard:null,prize:null,prizeId:null,prizeMap:[],drawnAt:null,finalized:false};if(!temBanco()){load().participations.push(x);save();return{participation:pubPart(x),createdNow:true}}try{const r=(await query('INSERT INTO participations(id,participant_id,round_id,prize_snapshot,entered_at)VALUES($1,$2,$3,$4::jsonb,NOW())RETURNING *',[x.id,x.participantId,x.roundId,JSON.stringify(snapshot)])).rows[0];return{participation:mapPart(r),createdNow:true}}catch(e){if(e.code==='23505')return{participation:await getParticipationByParticipantId(p.id),createdNow:false};throw e}}
async function finalizeParticipation(id,{selectedCard,prize,prizeId,prizeMap}){if(!temBanco()){const x=load().participations.find(p=>p.participantId===id);if(!x)throw new Error('Entrada não encontrada.');if(x.finalized)return{participation:pubPart(x),createdNow:false};Object.assign(x,{selectedCard,prize,prizeId:prizeId||null,prizeMap,drawnAt:now(),finalized:true});save();return{participation:pubPart(x),createdNow:true}}const rows=(await query('UPDATE participations SET selected_card=$1,prize=$2,prize_id=$3,prize_map=$4::jsonb,drawn_at=NOW(),finalized=TRUE WHERE participant_id=$5 AND finalized=FALSE RETURNING *',[selectedCard,prize,prizeId||null,JSON.stringify(prizeMap),id])).rows;return rows[0]?{participation:mapPart(rows[0]),createdNow:true}:{participation:await getParticipationByParticipantId(id),createdNow:false}}
async function listResults({search='',prize='',limit=500}={}){await initialize();const t=normalizarTexto(search,100).toLowerCase(),pf=normalizarTexto(prize,200).toLowerCase(),lim=Math.min(2000,Number(limit)||500);if(!temBanco()){const b=load();return b.participations.filter(x=>x.finalized).map(x=>({...pubPart(x),participant:pubP(b.participants.find(p=>p.id===x.participantId))})).filter(x=>!t||[x.participant?.code,x.participant?.name,x.participant?.contact].some(v=>String(v||'').toLowerCase().includes(t))).filter(x=>!pf||String(x.prize||'').toLowerCase().includes(pf)).sort((a,b)=>String(b.drawnAt).localeCompare(String(a.drawnAt))).slice(0,lim)}const ps=[],f=['pa.finalized=TRUE'];if(t){ps.push(`%${t}%`);f.push(`(LOWER(p.code)LIKE $${ps.length} OR LOWER(p.name)LIKE $${ps.length} OR LOWER(p.contact)LIKE $${ps.length})`)}if(pf){ps.push(`%${pf}%`);f.push(`LOWER(pa.prize)LIKE $${ps.length}`)}ps.push(lim);const rows=(await query(`SELECT pa.*,p.code,p.name,p.contact,p.active,p.fixed_prize,p.created_at participant_created_at,p.updated_at participant_updated_at FROM participations pa JOIN participants p ON p.id=pa.participant_id WHERE ${f.join(' AND ')} ORDER BY pa.drawn_at DESC LIMIT $${ps.length}`,ps)).rows;return rows.map(r=>({...mapPart(r),participant:pubP({id:r.participant_id,code:r.code,name:r.name,contact:r.contact,active:r.active,fixedPrize:r.fixed_prize,createdAt:r.participant_created_at,updatedAt:r.participant_updated_at})}))}
async function savePayment(participantId,data){
 await initialize();
 if(!temBanco()){
  const x=load().participations.find(x=>x.participantId===participantId);
  if(!x?.finalized)throw new Error('Sorteio ainda não realizado.');
  if(x.paymentAt) return {participation:pubPart(x),createdNow:false};
  x.paymentData=data;x.paymentAt=now();x.paymentNotificationStatus='pending';save();
  return {participation:pubPart(x),createdNow:true};
 }
 const rows=(await query(`UPDATE participations SET payment_data=$1::jsonb,payment_at=NOW(),payment_notification_status='pending' WHERE participant_id=$2 AND finalized=TRUE AND payment_at IS NULL RETURNING *`,[JSON.stringify(data),participantId])).rows;
 return rows.length?{participation:mapPart(rows[0]),createdNow:true}:{participation:await getParticipationByParticipantId(participantId),createdNow:false};
}
async function setPaymentNotificationStatus(participantId,status){
 await initialize();
 if(!temBanco()){const x=load().participations.find(x=>x.participantId===participantId);if(x){x.paymentNotificationStatus=status;save()}return;}
 await query('UPDATE participations SET payment_notification_status=$1 WHERE participant_id=$2',[status,participantId]);
}
async function getDashboard(){await initialize();if(!temBanco()){const b=load(),done=b.participations.filter(x=>x.finalized);return{totalParticipants:b.participants.length,activeParticipants:b.participants.filter(x=>x.active).length,enteredParticipants:b.participations.length,completedParticipants:done.length,totalPrizeCards:b.prizes.filter(x=>x.active).reduce((s,x)=>s+Number(x.quantity||0),0),recentResults:await listResults({limit:8})}}const r=(await query(`SELECT(SELECT COUNT(*)::int FROM participants)total_participants,(SELECT COUNT(*)::int FROM participants WHERE active=TRUE)active_participants,(SELECT COUNT(*)::int FROM participations)entered_participants,(SELECT COUNT(*)::int FROM participations WHERE finalized=TRUE)completed_participants,(SELECT COALESCE(SUM(quantity),0)::int FROM prizes WHERE active=TRUE)total_prize_cards`)).rows[0];return{totalParticipants:r.total_participants,activeParticipants:r.active_participants,enteredParticipants:r.entered_participants,completedParticipants:r.completed_participants,totalPrizeCards:r.total_prize_cards,recentResults:await listResults({limit:8})}}
module.exports={initialize,getSettings,updateSettings,listParticipants,findParticipantByCode,getParticipantById,createParticipant,updateParticipant,deleteParticipant,resetParticipation,listPrizes,createPrize,updatePrize,deletePrize,getParticipationByParticipantId,registerEntry,finalizeParticipation,savePayment,setPaymentNotificationStatus,listResults,getDashboard,audit};
